{ config, pkgs, ... }:

{
  imports =
    [
      ../profiles/android.nix
      ../profiles/audio.nix
      ../profiles/desktop.nix
      ../profiles/development.nix
      ../profiles/docker.nix
      ../profiles/drawing.nix
      ../profiles/email.nix
      ../profiles/games.nix
      ../profiles/graphics.nix
      ../profiles/networking.nix
      ../profiles/laptop.nix
      ../profiles/mathematics.nix
      ../profiles/printing.nix
      ../profiles/redshift.nix
      ../profiles/steam.nix
      ../profiles/virtualization.nix

      # Experimental
    ];

#  networking.firewall.enable = false;
  networking.firewall.allowPing = true;

# Set a static IP when I didn't want to set up dhcp
#  networking.defaultGateway = "192.168.0.1";
#  networking.interfaces.enp3s0 = {
#    ipAddress = "192.168.0.42";
#    prefixLength = 24;
#  };

  hardware.opengl.driSupport32Bit = true;

#  # Use the GRUB 2 boot loader.
#  boot.loader.grub.enable = true;
#  boot.loader.grub.version = 2;
#  # Define on which hard drive you want to install Grub.
#  boot.loader.grub.device = "/dev/sda";

  # Use the efi boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Speed up development at the cost of possible build race conditions
  nix.buildCores = 8;

  # Generated by nvidia-settings.
  services.xserver = {

    # Use the NVIDIA graphics drivers.
    videoDrivers = [ "nvidia" ];

#    serverLayoutSection = ''
#      Option         "Xinerama" "0"
#    '';
#
#    monitorSection = ''
#      # HorizSync source: edid, VertRefresh source: edid
#      VendorName     "Unknown"
#      ModelName      "Ancor Communications Inc VE228"
#      HorizSync       30.0 - 83.0
#      VertRefresh     50.0 - 76.0
#      Option         "DPMS"
#    '';
#
#    deviceSection = ''
#      Driver         "nvidia"
#      VendorName     "NVIDIA Corporation"
#      BoardName      "GeForce GTX 670"
#    '';
#
#    screenSection = ''
#      DefaultDepth    24
#      Option         "Stereo" "0"
#      Option         "metamodes" "DVI-I-1: nvidia-auto-select +0+0 {rotation=left}, DP-0: nvidia-auto-select +1080+0 {rotation=left}, DVI-D-0: nvidia-auto-select +2160+0 {rotation=left}; DVI-I-1: nvidia-auto-select +0+0 {rotation=left}; DVI-I-1: 1680x1050 +0+0 {rotation=left}; DVI-I-1: 1600x1200 +0+0 {rotation=left}; DVI-I-1: 1440x900 +0+0 {rotation=left}; DVI-I-1: 1280x1024 +0+0 {rotation=left}; DVI-I-1: 1280x1024_60 +0+0 {rotation=left}; DVI-I-1: 1280x960 +0+0 {rotation=left}; DVI-I-1: 1152x864 +0+0 {rotation=left}; DVI-I-1: 1024x768 +0+0 {rotation=left}; DVI-I-1: 1024x768_70 +0+0 {rotation=left}; DVI-I-1: 1024x768_60 +0+0 {rotation=left}; DVI-I-1: 800x600 +0+0 {rotation=left}; DVI-I-1: 800x600_72 +0+0 {rotation=left}; DVI-I-1: 800x600_60 +0+0 {rotation=left}; DVI-I-1: 800x600_56 +0+0 {rotation=left}; DVI-I-1: 640x480 +0+0 {rotation=left}; DVI-I-1: 640x480_72 +0+0 {rotation=left}; DVI-I-1: 640x480_60 +0+0 {rotation=left}"
#      Option         "SLI" "Off"
#      Option         "MultiGPU" "Off"
#      Option         "BaseMosaic" "off"
#      SubSection     "Display"
#          Depth       24
#      EndSubSection
#    '';
  };
}
